#!/usr/bin/expect
spawn su - root
expect "Password:"
send "niuge\r"
expect "*"
send "nohup /usr/local/bin/sslocal -c  /opt/proxy/shadowsocks/shadowsocks.json 2>&1 >>/var/log/shadowsocks.log &"
expect "*"
send "exit\r"

interact
